/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import static java.applet.Applet.newAudioClip;
import java.applet.AudioClip;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Casa
 */
public class FRM_InicioJuego extends javax.swing.JFrame {

    /**
     * Creates new form FRM_InicioJuego
     */
    AudioClip sonido = newAudioClip(getClass().getResource("/audios/inicio.wav"));

    FRM_Instrucciones fRM_Instrucciones = new FRM_Instrucciones();
    FRM_Puntajes fRM_Puntajes = new FRM_Puntajes();
    FRM_VentanaJuego fRM_VentanaJuego= new FRM_VentanaJuego();
    
    String estadoSonido="";
    public FRM_InicioJuego() {
        initComponents();
        setLocationRelativeTo(this);
        sonido.loop();
        estadoSonido="Sonando";
        labelSonido.setIcon(new ImageIcon("src/imagenes/on.png"));
        
    }
    
    public void listar()
    {
        
        fRM_Puntajes.mostrarPuntajes(fRM_VentanaJuego.fRM_IngresarPuntaje.metodosPuntaje.getInformacionArchivosPlanos());
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelSonido = new javax.swing.JLabel();
        btnJugar = new javax.swing.JButton();
        btnInstrucciones = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnPuntajes = new javax.swing.JButton();
        labelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(950, 690));
        getContentPane().setLayout(null);

        labelSonido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelSonidoMouseClicked(evt);
            }
        });
        getContentPane().add(labelSonido);
        labelSonido.setBounds(780, 20, 50, 30);

        btnJugar.setBackground(new java.awt.Color(0, 255, 0));
        btnJugar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1465533269_Play01.png"))); // NOI18N
        btnJugar.setText("Jugar");
        btnJugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJugarActionPerformed(evt);
            }
        });
        getContentPane().add(btnJugar);
        btnJugar.setBounds(100, 590, 110, 30);

        btnInstrucciones.setBackground(new java.awt.Color(255, 255, 51));
        btnInstrucciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1465533442_list.png"))); // NOI18N
        btnInstrucciones.setText("Instrucciones");
        btnInstrucciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInstruccionesActionPerformed(evt);
            }
        });
        getContentPane().add(btnInstrucciones);
        btnInstrucciones.setBounds(260, 590, 150, 30);

        btnSalir.setBackground(new java.awt.Color(255, 0, 0));
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1465533528_No.png"))); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir);
        btnSalir.setBounds(460, 590, 120, 30);

        btnPuntajes.setBackground(new java.awt.Color(255, 153, 51));
        btnPuntajes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1465889934_moderator.png"))); // NOI18N
        btnPuntajes.setText("Mejores puntuaciones");
        btnPuntajes.setToolTipText("");
        btnPuntajes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPuntajesActionPerformed(evt);
            }
        });
        getContentPane().add(btnPuntajes);
        btnPuntajes.setBounds(670, 90, 230, 50);

        labelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/kayakFondo.png"))); // NOI18N
        getContentPane().add(labelFondo);
        labelFondo.setBounds(0, 0, 940, 720);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInstruccionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInstruccionesActionPerformed
        // TODO add your handling code here:
        fRM_Instrucciones.setVisible(true);
        
    }//GEN-LAST:event_btnInstruccionesActionPerformed

    private void btnJugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJugarActionPerformed
        // TODO add your handling code here:
        fRM_VentanaJuego= new FRM_VentanaJuego();
        fRM_VentanaJuego.iniciarJuego();
        fRM_VentanaJuego.setVisible(true);
        
        sonido.stop();
        estadoSonido="stop";
        labelSonido.setIcon(new ImageIcon("src/imagenes/mute.png"));

    }//GEN-LAST:event_btnJugarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        int x = JOptionPane.showConfirmDialog(this, "Desea salir");
        if(x == 0)
            System.exit(0);
        
            
    }//GEN-LAST:event_btnSalirActionPerformed

    private void labelSonidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelSonidoMouseClicked
        // TODO add your handling code here:
        if(estadoSonido.equalsIgnoreCase("Sonando"))
        {
            sonido.stop();
            estadoSonido="stop";
            labelSonido.setIcon(new ImageIcon("src/imagenes/mute.png"));
        }
        else
        {
            sonido.loop();
            estadoSonido="Sonando";
            labelSonido.setIcon(new ImageIcon("src/imagenes/on.png"));
        }
        
    }//GEN-LAST:event_labelSonidoMouseClicked

    private void btnPuntajesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPuntajesActionPerformed
        // TODO add your handling code here:
        listar();
        fRM_Puntajes.setVisible(true);
    }//GEN-LAST:event_btnPuntajesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FRM_InicioJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FRM_InicioJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FRM_InicioJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FRM_InicioJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FRM_InicioJuego().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInstrucciones;
    private javax.swing.JButton btnJugar;
    private javax.swing.JButton btnPuntajes;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel labelFondo;
    private javax.swing.JLabel labelSonido;
    // End of variables declaration//GEN-END:variables
}
